### ISSUE TITLE
Uncaught exception with certain amount of presets

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion-module-barco-eventmaster#30] opened 2020-05-01 04:28 UTC
The following error occurs on a certain show file with lots of presets

`Uncaught Exception:
TypeError: fixtext.match is not a function
    at instance.setPresetDefinitions (/Applications/Companion.app/Contents/Resources/app.asar/lib/instance_skel.js:225:16)
    at instance.initPresets (/Applications/Companion.app/Contents/Resources/app.asar/lib/module/eventmaster/eventmaster.js:779:7)
    at instance.retry (/Applications/Companion.app/Contents/Resources/app.asar/lib/module/eventmaster/eventmaster.js:123:7)
    at cb (/Applications/Companion.app/Contents/Resources/app.asar/electron-timer-fix/index.js:129:7)
    at ChildProcess.cp.fork.on (/Applications/Companion.app/Contents/Resources/app.asar/electron-timer-fix/index.js:93:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)` 

The EM has around 100 presets with numbering such as 81.01 etc.

**Comment by krocheck** [comment] 2020-05-01 05:08
@JeffreyDavidsz one of the CHOICE lists is ending up a with label that is `undefined`.  I'm guessing `CHOICES_CUES`.  It's getting hung up in the processing block to pre-parse the dynamic variables.  I'll patch this exception in the core, but it might be good to figure out why a label is coming through undefined and mitigate it.

**Comment by JeffreyDavidsz** [comment] 2020-05-01 06:06
#25

**Comment by krocheck** [comment] 2020-05-01 12:56
Duplicate of #25

**Closed by krocheck** 2020-05-01 12:56 UTC
